b_test_task/api/urls.py
from rest_framework import routers

from api.views import EventViewSet, EventRegistrationViewSet


router = routers.DefaultRouter()
router.register(r'events', EventViewSet, 'event-api')
router.register(r'event_register', EventRegistrationViewSet, 
                    'event_register')

urlpatterns = router.urls

b_test_task/b_test_task/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('loginsys.urls')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include(('event.urls', 'event'), namespace='event')),
]

b_test_task/event/urls.py
from django.urls import path
from event.views import (
     main_page, 
     event_list,
     event_detail,
     register_on_event,
)


urlpatterns = [
     path('', main_page, name='home'),
     path('event_list', event_list, name='event_list'),
     path('event/<int:event_id>', event_detail, name='event_detail'),
     path('event_register', register_on_event, name='event_register'),
]

b_test_task/loginsys/urls.py
from django.urls import path
from loginsys.views import register_view, login_view, logout_view


urlpatterns = [
     path('register/', register_view, name='register'),
     path('logout/', logout_view, name='logout'),
     path('login/',  login_view, name='login'),
]

b_test_task/event/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    start_dt = models.DateTimeField(verbose_name='Start time')

    def __str__(self):
        return self.title


class EventRegistration(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

b_test_task/event/forms.py
from django.forms import ModelForm
from event.models import EventRegistration


class EventRegistrationForm(ModelForm):
    class Meta:
        model = EventRegistration
        fields = ['event', 'user']

b_test_task/loginsys/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "password1", "password2")

    def save(self, commit: bool = True) -> User:
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

b_test_task/api/views.py
from django.shortcuts import get_object_or_404

from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication
from rest_framework import permissions
from rest_framework.request import Request

from event.models import Event
from .serializers import (
    EventListSerializer, 
    EventDetailSerializer,
    EventRegistrationSerializer
)


class EventViewSet(viewsets.ViewSet):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    def list(self, request: Request) -> Response:
        queryset = Event.objects.all()
        serializer = EventListSerializer(queryset, many=True, context={'request': request})
        return Response(serializer.data)

    def retrieve(self, request: Request, pk: int=None) -> Response:
        queryset = Event.objects.all()
        event = get_object_or_404(queryset, id=pk)
        serializer = EventDetailSerializer(event)
        return Response(serializer.data)


class EventRegistrationViewSet(viewsets.ViewSet):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    authentication_classes = [SessionAuthentication]

    def create(self, request: Request, *args, **kwargs) -> Response:
        data = {
            'event': request.data['event'],
            'user': request.user.id
        }
        serializer = EventRegistrationSerializer(data=data)
        serializer.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)

   

b_test_task/event/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.http.request import HttpRequest
from django.http.response import HttpResponse

from event.utils.event_helpers import (
    get_active_events,
    get_event_by_id,
    get_is_user_on_event,
)
from event.forms import EventRegistrationForm


def main_page(request: HttpRequest) -> HttpResponse:
    print(request)
    if request.user.is_authenticated:
        return render(request, 'event/home_page.html', context={})
    else: 
        return redirect('login')


@login_required
def event_list(request: HttpRequest) -> HttpResponse:
    data = {}
    events = get_active_events()
    data['events'] = events
    return render(request, 'event/event_list.html', context=data)


@login_required
def event_detail(request: HttpRequest, event_id: int) -> HttpResponse:
    data = {}
    data['event'] = get_event_by_id(event_id)
    data['on_event'] = get_is_user_on_event(event_id, request.user.id)
    return render(request, 'event/event_detail.html', context=data)


@login_required
@require_http_methods(["POST"])
def register_on_event(request: HttpRequest) -> HttpResponse:
    if get_is_user_on_event(
        request.POST.get('event'), request.POST.get('user')
        ):
        redirect(
            'event:event_detail', 
            event_id=request.POST.get('event')
            )

    form = EventRegistrationForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect(
            'event:event_detail', 
            event_id=request.POST.get('event')
            )

b_test_task/loginsys/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.request import HttpRequest
from django.http.response import HttpResponse

from .forms import RegisterForm, LoginForm


def register_view(request: HttpRequest) -> HttpResponse:
    if request.user.is_authenticated:
        return redirect('client:home')
    if request.method == 'GET':
        form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('event:home')
  
    return render(request, 'registration/register.html', 
        {'register_form':form})


def login_view(request: HttpRequest) -> HttpResponse:
    data = {}
    if request.method == 'GET':
        form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            
            user = authenticate(request, username=cd['username'], 
                password=cd['password'])
            if user is not None:
                login(request, user)
                return redirect('event:home')
            data['error'] = 'Логин или пароль неверный!'
    data['form'] = form
    return render(request, 'registration/login.html', data)


@login_required
def logout_view(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect('event:home')

b_test_task/templates/error_page.html
{% extends "index.html" %}

{% block content %}
<div class="container py-5 ">
    <h3>Ошибка! Не удалось получить данные от TeachBase.</h3>
    <p>{{error | safe}}</p>
</div>
{% endblock %}

b_test_task/templates/event/event_detail.html
{% extends "index.html" %}

{% block content %}
    <div class="container py-5 ">
        <h4>{{event.title}}</h4>
        <br>
        <p>{{event.description | safe}}</p>
        </br>
        {% if on_event %}
            <div>
                <p>Вы зарегистрированы на это событие</p>
            </div>
        {% else %}
            <form method="post" action="{% url 'event:event_register' %}">
                {% csrf_token %}
                <input type="hidden" name="event" value="{{event.id}}">
                <input type="hidden" name="user" value="{{user.id}}">
                <button type="submit" class="btn btn-outline-success">Зарегистрироваться</button>
            </form>
        {% endif %}
        <hr>
        <p class="text-muted">Мероприятие состоится {{event.start_dt | date:"d/m/Y"}} в {{event.start_dt | date:"H:i"}}</p>
    </div>
{% endblock %}

b_test_task/templates/event/event_list.html
{% extends "index.html" %}

{% block content %}
    <div class="">
        {% for e in events %}
            <div class="card" style="margin: 10px;">
                <div class="card-body">
                    <h5 class="card-title">{{e.title}}</h5>
                    <p class="card-text">{{e.description | slice:':100'}}...</p>
                </div>
                <div class="card-footer">
                    <p class="card-text text-end"><small class="text-muted">Начало: {{e.start_dt | date:"d/m/Y H:i " }}</small></p>
                    <a href="{% url 'event:event_detail' event_id=e.id %}" class="btn btn-secondary" tabindex="-1" role="button" aria-disabled="true">Подробнее</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

b_test_task/templates/event/home_page.html
{% extends "index.html" %}

{% block content %}
  <ul class="list-group">
    <li class="list-group-item list-group-item-dark" aria-current="true">Данные об аккаунте</li>
    <li class="list-group-item">
        <table class="table">
            <tbody>
              <tr>
                <td>Username</td>
                <td>{{user.username}}</td>
              </tr>
              <tr>
                <td>Name</td>
                <td>{{user.first_name}}</td>
              </tr>
              <tr>
                <td>Email</td>
                <td>{{user.email}}</td>
              </tr>
            </tbody>
        </table>
    </li>
  </ul>
{% endblock %}

b_test_task/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event scheduler</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Event scheduler</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'event:event_list'%}">Мероприятия</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/api/events/">API</a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            
                <div class="d-flex" role="search">
                    <div class="navbar-nav me-auto mb-2 mb-lg-0">
                        <div class="nav-item" style="margin-right: 30px;">
                            <span class="nav-link disabled">{{user.first_name}}</span>
                        </div>
                </div>
                    <a href="{% url 'logout' %}?next=/" class="btn btn-outline-danger" tabindex="-1" role="button" aria-disabled="true">Выйти </a>
                </div>
            {% endif %}
        </div>
    </nav>
    {% if user.is_authenticated %}
        {% block content %}
        {% endblock %}
    {% else %}
        {% block content_auth %}
        {% endblock %}
    {% endif %}
</body>
</html>